### ISSUE TITLE
how to load data for fund balance

### ISSUE THREAD

**Issue by anizeani** [itering/subscan-api-docs#9]
I’m trying to get the data for the fund balance for a specific ParaId as shown for example here:
https://kusama.subscan.io/crowdloan/2004-6?tab=fund_balance

Reading the api documentation I found those two calls: 
1. POST /api/scan/parachain/funds
2. POST /api/scan/parachain/contributes

I figured, if I use the 2nd call with the specified paraId in the body of my POST, I could get all the contributions and sum them up over time, but I see there are many rows and pages, and I'm not sure that calling so many calls to retrieve all pages would be the right approach..

Does anybody know how to do it?

**Comment by carlhong** [comment]
If you want the sum of raised balance , you can use /api/scan/parachain/funds.
The second api is for contributions history.
